# scripts/utils/make_report_figs_cls.py
from __future__ import annotations

import os
import re
import json
from pathlib import Path
from typing import Dict, Any, List, Optional, Tuple

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

PROJECT_ROOT = Path(__file__).resolve().parents[2]
OUTPUTS = PROJECT_ROOT / "outputs"
REPORT_DIR = OUTPUTS / "report_cls"
REPORT_DIR.mkdir(parents=True, exist_ok=True)

EXP1_CSV = OUTPUTS / "exp1_summary.csv"  # generated by summarize_exp1.py

EXP2_LORA_DIR = OUTPUTS / "exp2_lora"
EXP2_EORA_DIR = OUTPUTS / "exp2_eora"

# ---------- helpers ----------
def _safe_float(x, default=np.nan):
    try:
        return float(x)
    except Exception:
        return default

def _read_json(path: Path) -> Optional[Dict[str, Any]]:
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception:
        return None

def _parse_run_name(run_name: str) -> Dict[str, Any]:
    """
    exp run folder names like:
      r16_ar4
      r64_ar1.25_T1
    """
    out = {"rank": np.nan, "ar": np.nan, "T": np.nan}
    m = re.search(r"r(\d+)", run_name)
    if m:
        out["rank"] = int(m.group(1))
    m = re.search(r"ar([0-9.]+)", run_name)
    if m:
        out["ar"] = float(m.group(1))
    m = re.search(r"_T([0-9.]+)", run_name)
    if m:
        out["T"] = float(m.group(1))
    return out

def _scan_exp2_runs(root: Path, tag: str) -> pd.DataFrame:
    """
    Scan outputs/exp2_lora/*/metrics.json and outputs/exp2_eora/*/metrics.json
    Expect metrics.json like:
      {"val": {...}, "test.py": {...}, "config": {...}}  OR your own layout.
    We'll be robust and try common keys.
    """
    rows = []
    if not root.exists():
        return pd.DataFrame()

    for run_dir in sorted([p for p in root.iterdir() if p.is_dir()]):
        metrics_path = run_dir / "metrics.json"
        j = _read_json(metrics_path)
        if j is None:
            # try fallback: any json file
            cand = list(run_dir.glob("*.json"))
            if cand:
                j = _read_json(cand[0])
        if j is None:
            continue

        meta = _parse_run_name(run_dir.name)

        # try to find test.py dict
        test = j.get("test.py", j.get("Test", j.get("metrics_test", j)))
        val = j.get("val", j.get("Val", j.get("metrics_val", {})))

        row = {
            "branch": tag,
            "run": run_dir.name,
            "rank": meta["rank"],
            "ar": meta["ar"],
            "T": meta["T"],
            # metrics (robust keys)
            "test_acc": _safe_float(test.get("accuracy", test.get("acc", np.nan))),
            "test_ce": _safe_float(test.get("ce_loss", test.get("loss", np.nan))),
            "test_kl": _safe_float(test.get("kl_to_teacher", test.get("kl", np.nan))),
            "test_mse": _safe_float(test.get("mse_logits_to_teacher", test.get("mse", np.nan))),
            "val_acc": _safe_float(val.get("accuracy", val.get("acc", np.nan))),
            "val_ce": _safe_float(val.get("ce_loss", val.get("loss", np.nan))),
            "val_kl": _safe_float(val.get("kl_to_teacher", val.get("kl", np.nan))),
            "val_mse": _safe_float(val.get("mse_logits_to_teacher", val.get("mse", np.nan))),
            "metrics_path": str(metrics_path),
        }
        rows.append(row)

    return pd.DataFrame(rows)

def _pivot_heatmap(df: pd.DataFrame, value_col: str, title: str, out_png: Path):
    """
    Heatmap of value_col over (rank, ar). One branch at a time.
    """
    if df.empty:
        return

    p = df.pivot_table(index="rank", columns="ar", values=value_col, aggfunc="max")
    p = p.sort_index().sort_index(axis=1)

    fig = plt.figure(figsize=(10, 4))
    ax = plt.gca()
    im = ax.imshow(p.values, aspect="auto")
    ax.set_title(title)
    ax.set_xlabel("alpha/r (ar)")
    ax.set_ylabel("rank (r)")

    ax.set_xticks(range(len(p.columns)))
    ax.set_xticklabels([str(c) for c in p.columns])
    ax.set_yticks(range(len(p.index)))
    ax.set_yticklabels([str(i) for i in p.index])

    plt.colorbar(im, ax=ax)
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close(fig)

def _best_by(df: pd.DataFrame, sort_key: str, higher_is_better: bool = True) -> pd.DataFrame:
    if df.empty:
        return df
    df2 = df.copy()
    df2 = df2.dropna(subset=[sort_key])
    df2 = df2.sort_values(sort_key, ascending=not higher_is_better)
    return df2.head(1)

def _line_best_over_rank(df: pd.DataFrame, value_col: str, title: str, out_png: Path):
    """
    For each rank: take best over ar, then plot vs rank.
    """
    if df.empty:
        return
    g = df.dropna(subset=["rank", value_col]).groupby("rank")[value_col].max().reset_index()
    g = g.sort_values("rank")

    fig = plt.figure(figsize=(6, 4))
    ax = plt.gca()
    ax.plot(g["rank"], g[value_col], marker="o")
    ax.set_title(title)
    ax.set_xlabel("rank (r)")
    ax.set_ylabel(value_col)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close(fig)

def _scatter_kl_mse_acc(df: pd.DataFrame, title: str, out_png: Path):
    """
    Scatter: x=KL, y=MSE, point size by Acc (or color by Acc).
    """
    if df.empty:
        return
    d = df.dropna(subset=["test_kl", "test_mse", "test_acc"]).copy()
    if d.empty:
        return

    fig = plt.figure(figsize=(7, 5))
    ax = plt.gca()
    sc = ax.scatter(d["test_kl"], d["test_mse"], c=d["test_acc"], s=60, alpha=0.85)
    ax.set_title(title)
    ax.set_xlabel("Test KL to teacher (lower better)")
    ax.set_ylabel("Test MSE logits to teacher (lower better)")
    cb = plt.colorbar(sc, ax=ax)
    cb.set_label("Test accuracy (higher better)")
    ax.grid(True, alpha=0.25)
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close(fig)

def _bar_best_compare(best_a: pd.DataFrame, best_b: pd.DataFrame, metric: str, title: str, out_png: Path):
    if best_a.empty or best_b.empty:
        return
    labels = [best_a.iloc[0]["branch"], best_b.iloc[0]["branch"]]
    values = [best_a.iloc[0][metric], best_b.iloc[0][metric]]

    fig = plt.figure(figsize=(5, 4))
    ax = plt.gca()
    ax.bar(labels, values)
    ax.set_title(title)
    ax.set_ylabel(metric)
    for i, v in enumerate(values):
        ax.text(i, v, f"{v:.4f}", ha="center", va="bottom")
    plt.tight_layout()
    plt.savefig(out_png, dpi=200)
    plt.close(fig)

# ---------- main ----------
def main():
    # ======================
    # EXP1 (classification): read exp1_summary.csv
    # ======================
    if EXP1_CSV.exists():
        exp1 = pd.read_csv(EXP1_CSV)
        # expect columns like: branch, run, rank, ar, val_acc, test_acc ...
        # If your CSV differs, adjust mapping here.
        # Try to normalize:
        colmap = {c.lower(): c for c in exp1.columns}
        # required
        for need in ["branch", "run"]:
            if need not in colmap:
                # guess from existing
                pass

        # build normalized frame
        def pick(name, default=None):
            return exp1[colmap[name]] if name in colmap else default

        # tolerate different naming
        def getcol(*names):
            for n in names:
                if n in colmap:
                    return exp1[colmap[n]]
            return None

        exp1_norm = pd.DataFrame({
            "branch": getcol("branch", "type"),
            "run": getcol("run", "name"),
            "rank": getcol("rank", "r"),
            "ar": getcol("ar", "alpha_over_r"),
            "val_acc": getcol("val_acc", "val_accuracy"),
            "test_acc": getcol("test_acc", "test_accuracy"),
        })

        exp1_norm["rank"] = pd.to_numeric(exp1_norm["rank"], errors="coerce")
        exp1_norm["ar"] = pd.to_numeric(exp1_norm["ar"], errors="coerce")
        exp1_norm["val_acc"] = pd.to_numeric(exp1_norm["val_acc"], errors="coerce")
        exp1_norm["test_acc"] = pd.to_numeric(exp1_norm["test_acc"], errors="coerce")

        # split
        exp1_lora = exp1_norm[exp1_norm["branch"].str.contains("lora", case=False, na=False)].copy()
        exp1_eora = exp1_norm[exp1_norm["branch"].str.contains("eora", case=False, na=False)].copy()

        # heatmaps
        _pivot_heatmap(exp1_lora, "test_acc", "EXP1 LoRA: Test Accuracy heatmap (rank vs ar)", REPORT_DIR / "exp1_lora_testacc_heatmap.png")
        _pivot_heatmap(exp1_eora, "test_acc", "EXP1 EoRA: Test Accuracy heatmap (rank vs ar)", REPORT_DIR / "exp1_eora_testacc_heatmap.png")

        # best over rank curves
        _line_best_over_rank(exp1_lora, "test_acc", "EXP1 LoRA: best test_acc per rank", REPORT_DIR / "exp1_lora_best_over_rank.png")
        _line_best_over_rank(exp1_eora, "test_acc", "EXP1 EoRA: best test_acc per rank", REPORT_DIR / "exp1_eora_best_over_rank.png")

        # best compare bar
        best_lora = _best_by(exp1_lora, "test_acc", higher_is_better=True)
        best_eora = _best_by(exp1_eora, "test_acc", higher_is_better=True)
        _bar_best_compare(best_lora, best_eora, "test_acc", "EXP1: Best test_acc (LoRA vs EoRA)", REPORT_DIR / "exp1_best_testacc_bar.png")

        # save a clean exp1 table
        exp1_norm.to_csv(REPORT_DIR / "exp1_runs_clean.csv", index=False)

    # ======================
    # EXP2 (output matching): scan metrics.json
    # ======================
    exp2_lora = _scan_exp2_runs(EXP2_LORA_DIR, "LoRA")
    exp2_eora = _scan_exp2_runs(EXP2_EORA_DIR, "EoRA")
    exp2 = pd.concat([exp2_lora, exp2_eora], ignore_index=True)

    if not exp2.empty:
        exp2.to_csv(REPORT_DIR / "exp2_summary.csv", index=False)

        # scatter KL-MSE with acc color
        _scatter_kl_mse_acc(exp2_lora, "EXP2 LoRA: (KL, MSE) with Accuracy color", REPORT_DIR / "exp2_lora_scatter_kl_mse_acc.png")
        _scatter_kl_mse_acc(exp2_eora, "EXP2 EoRA: (KL, MSE) with Accuracy color", REPORT_DIR / "exp2_eora_scatter_kl_mse_acc.png")

        # KL heatmap (rank vs ar), per branch
        def hm(df, metric, name):
            _pivot_heatmap(df.rename(columns={"test_kl": metric}), metric,
                           f"EXP2 {name}: {metric} heatmap (rank vs ar)", REPORT_DIR / f"exp2_{name.lower()}_{metric}_heatmap.png")

        # easier: reuse pivot function but pass correct column
        _pivot_heatmap(exp2_lora.rename(columns={"test_kl": "KL"}), "KL", "EXP2 LoRA: Test KL heatmap (rank vs ar)", REPORT_DIR / "exp2_lora_testkl_heatmap.png")
        _pivot_heatmap(exp2_eora.rename(columns={"test_kl": "KL"}), "KL", "EXP2 EoRA: Test KL heatmap (rank vs ar)", REPORT_DIR / "exp2_eora_testkl_heatmap.png")

        # best compare bars (acc & KL)
        best_lora_acc = _best_by(exp2_lora, "test_acc", higher_is_better=True)
        best_eora_acc = _best_by(exp2_eora, "test_acc", higher_is_better=True)
        _bar_best_compare(best_lora_acc, best_eora_acc, "test_acc", "EXP2: Best test_acc (LoRA vs EoRA)", REPORT_DIR / "exp2_best_testacc_bar.png")

        best_lora_kl = _best_by(exp2_lora, "test_kl", higher_is_better=False)
        best_eora_kl = _best_by(exp2_eora, "test_kl", higher_is_better=False)
        _bar_best_compare(best_lora_kl, best_eora_kl, "test_kl", "EXP2: Best (lowest) test_kl (LoRA vs EoRA)", REPORT_DIR / "exp2_best_testkl_bar.png")

    # ======================
    # EXP3 limitation page (classification -> LM)
    # ======================
    limitation = pd.DataFrame([
        {"Issue": "Teacher/Student objective mismatch", "Why it blocks Exp3": "Exp3 intended for LM (token-level) but current teacher is SST-2 classifier (sequence-level)."},
        {"Issue": "Dataset mismatch", "Why it blocks Exp3": "LM needs large unlabeled text; SST-2 is short sentences + labels, not suitable for LM perplexity metrics."},
        {"Issue": "Metric mismatch", "Why it blocks Exp3": "Exp3 likely wants PPL / next-token KL; classification reports accuracy/CE only."},
        {"Issue": "Adapter target mismatch", "Why it blocks Exp3": "LoRA/EoRA injection points for LM should cover MLP/attn projections consistently; classifier head dominates otherwise."},
    ])
    limitation.to_csv(REPORT_DIR / "exp3_blockers_table.csv", index=False)

    # quick markdown snippet for report
    md = []
    md.append("# Classification Experiments (Exp1/Exp2) – Figures & Tables\n")
    md.append("## Output directory\n")
    md.append(f"- {REPORT_DIR}\n")
    md.append("## Exp1 key figures\n")
    md.append("- exp1_lora_testacc_heatmap.png\n- exp1_eora_testacc_heatmap.png\n- exp1_lora_best_over_rank.png\n- exp1_eora_best_over_rank.png\n- exp1_best_testacc_bar.png\n")
    md.append("## Exp2 key figures\n")
    md.append("- exp2_lora_scatter_kl_mse_acc.png\n- exp2_eora_scatter_kl_mse_acc.png\n- exp2_lora_testkl_heatmap.png\n- exp2_eora_testkl_heatmap.png\n- exp2_best_testacc_bar.png\n- exp2_best_testkl_bar.png\n")
    md.append("## Tables\n")
    md.append("- exp1_runs_clean.csv\n- exp2_summary.csv\n- exp3_blockers_table.csv\n")

    with open(REPORT_DIR / "README_report_cls.md", "w", encoding="utf-8") as f:
        f.write("\n".join(md))

    print("Done. Generated files in:", REPORT_DIR)


if __name__ == "__main__":
    main()
