optimized_model_dir: "outputs/optimized_sst2/model"
quant_output_dir: "outputs/quantize_optimized_sst2"

data:
  dataset_name: "glue/sst2"

calibration_num_samples: 2048

# conda activate eora-gpu
# python scripts/core/02_train_quantized.py --config configs/quantize_optimized_sst2.yaml
