model_name: "gpt2"
task_type: "classification"
num_labels: 2
seed: 42

output_dir: "outputs/exp1_lora/r4_ar4"

data:
  dataset_name: "glue/sst2"
  dataset_config_name: null
  max_length: 128
  batch_size: 8
  num_workers: 0
  use_internal_test: true
  internal_test_size: 0.1

lora:
  rank: 4
  alpha: 16         # alpha/r = 4
  dropout: 0.1
  target_modules: ["c_attn", "c_proj"]

train:
  lr: 1e-4
  weight_decay: 0.01
  num_epochs: 3
  grad_clip: 1.0

optimized_model_dir: "outputs/optimized_sst2/model"
