model_name: "gpt2"
task_type: "classification"
num_labels: 2
seed: 42

output_dir: "outputs/exp1_eora/r4_ar1"
optimized_model_dir: "outputs/optimized_sst2/model"

data:
  dataset_name: "glue/sst2"
  dataset_config_name: null
  max_length: 128
  batch_size: 8
  num_workers: 0
  use_internal_test: true
  internal_test_size: 0.1

eora:
  rank: 4
  alpha: 4          # alpha/r = 1
  dropout: 0.0
  target_modules: ["c_attn", "c_proj"]
  svd_on_cpu: true
